name: R Package CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        R: [ '4.1', 'devel' ]  # Test with different versions of R

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}

    - name: Install system dependencies
      run: |
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R package dependencies
      run: |
        install.packages('remotes')
        remotes::install_deps(dependencies = TRUE)
        remotes::install_cran('testthat')  # Ensure testthat is installed

    - name: Run unit tests
      run: |
        Rscript -e 'devtools::test()'

    - name: Build figures
      run: |
        Rscript -e 'source("scripts/build_figures.R")'  # Adjust path to your figure script

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: tests/testthat/  # Adjust to your test output path
